config/routes.rb
Rails.application.routes.draw do
root 'users#index'  
get 'buildings/paid'
  resources :buildings do
    resources :installments
  end
  
  resources :installments
  get 'installments/mark_as_overdue'
  

  resources :users do
    resources :buildings
  end
  resources :users

end

app/models/installment.rb
class Installment < ActiveRecord::Base
	#after_save :check_overdue
	#validate :check_over_schedule
	validate :check_over_payment
	belongs_to :building
	#validate :update_overdue
	#before_action :overdue_transform
	#validate :overdue_transform
	validates_presence_of :amount, :details
	
	def overdue_transform
		self.installments.where( 'status =  ?  AND installment_date < ?'  , "scheduled", Date.today )
	end

	def check_over_payment
		total_installment_amount = self.building.installments.sum(:amount) + self.amount
		if total_installment_amount > self.building.net_budget
			errors.add(:amount, "Payment exceeding")
		end
	end

	def check_over_schedule
		if self.installment_date < Date.today
			errors.add(:installment_date, "Given date is Completed")
		end
	end

	

				
	

	def check_overdue
		#total_overdue = self.building.installments.where( 'status = ?', "overdue")

		if self.installment_date > Date.today
			errors.add(:installment_date, "Given date is not yet came")
		end

		#if self.building.installments.where( 'status = ?', "overdue")
			#total_overdue > self.building.installments.where( 'installment_date = ?', Time.created_at )
		#	errors.add(:status, "Please Collect Overdue Amount")

	end
end

app/controllers/installments_controller.rb
class InstallmentsController < ApplicationController
  before_action :set_installment, only: [:show, :edit, :update, :destroy]

  # GET /installments
  # GET /installments.json
  def index
    @installments = Installment.all
  end

  # GET /installments/1
  # GET /installments/1.json
  def show
    @installment = Installment.new
  end

  # GET /installments/new
  def new
    @installment = Installment.new
  end

  # GET /installments/1/edit
  def edit
  end

  # POST /installments
  # POST /installments.json
  def create
    @installment = Installment.new(installment_params)
    @building = @installment.building

    respond_to do |format|
      if @installment.save
        format.html { redirect_to building_path(@installment.building_id), notice: 'Installment was successfully created.' }
        format.json { render :show, status: :created, location: @installment }
      else
        format.html { render :new }
        format.json { render json: @installment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /installments/1
  # PATCH/PUT /installments/1.json
  def update
    respond_to do |format|
      if @installment.update(installment_params)
        format.html { redirect_to building_path(@installment.building_id), notice: 'Installment was successfully updated.' }
        format.json { render :show, status: :ok, location: @installment }
      else
        format.html { render :edit }
        format.json { render json: @installment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /installments/1
  # DELETE /installments/1.json
  def destroy
    @installment.destroy
    respond_to do |format|
      format.html { redirect_to building_path(@installment.building_id), notice: 'Installment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_installment
      @installment = Installment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def installment_params
      params.require(:installment).permit(:building_id, :amount, :installment_date, :status, :details)
    end
end

app/helpers/installments_helper.rb
module InstallmentsHelper
end

app/views/installments/_form.html.erb
<%= form_for([@building, @installment]) do |f| %>
  <% if @installment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@installment.errors.count, "error") %> prohibited this installment from being saved:</h2>

      <ul>
      <% @installment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fie">
    <%= f.hidden_field :building_id, value: @building.id %>
  </div>
  <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="form-group">
    <%= f.label :installment_date %><br>
    <%= f.date_select :installment_date %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, ["paid", "scheduled", "overdue"], {prompt: "Select" } %>
  </div>
  <div class="form-group">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/installments/edit.html.erb
<h1>Editing Installment</h1>

<%= render 'form' %>

<%= link_to 'Show', @installment %> |
<%= link_to 'Back', installments_path %>

app/views/installments/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-7">
    <div class="page header" >
      <h1>Listing Installments</h1>

    </div>






    <table class="table table-stiped">
      <thead>
        <tr>
          <th>Building</th>
          <th>Amount</th>
          <th>Installment date</th>
          <th>Status</th>
          <th>Details</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @installments.each do |installment| %>
        <tr>
          <td><%= installment.building_id %></td>
          <td><%= installment.amount %></td>
          <td><%= installment.installment_date %></td>
          <td><%= installment.status %></td>
          <td><%= installment.details %></td>
          <td><%= link_to 'Show', installment %></td>
          <td><%= link_to 'Edit', edit_installment_path(installment) %></td>
          <td><%= link_to 'Destroy', installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>


  <div class="col-md-5">
    <div class="page header" >
      <h1>Add  Installments</h1>

    </div>


    <%= link_to 'New Installment', new_installment_path, class: "btn btn-success" %>
  </div>
</div>

app/views/installments/new.html.erb
<h1>New Installment</h1>

<%= render 'form' %>

<%= link_to 'Back', installments_path %>

app/views/installments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building:</strong>
  <%= @installment.building_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @installment.amount %>
</p>

<p>
  <strong>Installment date:</strong>
  <%= @installment.installment_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @installment.status %>
</p>

<p>
  <strong>Details:</strong>
  <%= @installment.details %>
</p>

<%= link_to 'Edit', edit_installment_path(@installment) %> |
<%= link_to 'Back', installments_path %>