config/routes.rb
Rails.application.routes.draw do
root 'users#index'  
get 'buildings/paid'
  resources :buildings do
    resources :installments
  end
  
  resources :installments
  get 'installments/mark_as_overdue'
  

  resources :users do
    resources :buildings
  end
  resources :users

end

app/models/building.rb
class Building < ActiveRecord::Base
	before_save :calculate_net_budget
	belongs_to :user
	has_many :installments
	#validate :check_over_discount
	#before_save :overdue_transform
	validates_presence_of :title, :total_budget


	def overdue_transform
		self.installments.where( 'status =  ?  AND installment_date < ?'  , "scheduled", Date.today )
	end

	private

	def calculate_net_budget
		self.net_budget = self.total_budget - self.discount
	end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @installment = Installment.new
    @schedule_count = Installment.where("status = ?", "scheduled")
     @overdue_transform = Installment.where("status = ?", "overdue")
   @building = Building.find(params[:id])
  end

  def paid
    @pay = Installment.find(params[:installment_id])
    @pay.update_attribute(:status, "paid")
    redirect_to buildings_path
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
    @user = @building.user
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)
    @user = @building.user 
    respond_to do |format|
      if @building.save
        format.html { redirect_to user_path(@building.user_id), notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:title, :description, :total_budget, :discount, :net_budget, :user_id)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for([@user, @building]) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
   
    <%= f.hidden_field :user_id, value: @user.id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :total_budget %><br>
    <%= f.text_field :total_budget %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
 
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Total budget</th>
      <th>Discount</th>
      <th>Net budget</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.title %></td>
        <td><%= building.description %></td>
        <td><%= building.total_budget %></td>
        <td><%= building.discount %></td>
        <td><%= building.net_budget %></td>
        <td><%= building.user_id %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<div class="row">
<div class="col-md-4">
<p id="notice"><%= notice %></p>




<h3>Add Installment </h3>

<%= render '/installments/form' %>

<b> Total Balance Due - <%= @building.net_budget - @building.installments.where('status = ?', "paid").sum(:amount) %></b>

<b> Sum Paid - <%= @building.installments.where('status = ?', "paid").sum(:amount) %></b>

<b> Overdue  - <%= @building.installments.where('status = ?', "overdue").sum(:amount) %></b>

<b> Schedule  - <%= @building.installments.where('status = ?', "scheduled").sum(:amount) %></b>


<b> Remaining Amount - <% @building.installments.where('status = ?', "paid").sum(:amount) - ( @building.installments.where('status = ?', "scheduled").sum(:amount) + @building.installments.where('status = ?', "overdue").sum(:amount) ) %></b>


</div>
<div class="col-md-4">
<h3> Overdue Deals <%= @overdue_transform.count %> </h3>
<% @overdue_transform.each do |installment| %>
<li><%= installment.amount %></li>
<% end %>


<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3> Scheduled Deals <%= @schedule_count.count %> </h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>building</th>
      <th>Amount</th>
      <th>Installment date</th>
      <th>Status</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedule_count.each do |installment| %>
    <tr>
      <td><%= installment.building_id %></td>
      <td><%= installment.amount %></td>
      <td><%= installment.installment_date %></td>
      <td><%= installment.status %></td>
      <td><%= installment.details %></td>
      <% if installment.status != "paid" %>
      <td><%= link_to 'Pay', buildings_paid_path(:installment_id => installment.id) %></td>
      <td><%= link_to 'Edit', edit_installment_path(installment) %></td>
      <td><%= link_to 'Destroy', installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

</div>






</div>

<div class="col-md-4">


<div class="list-group">
  <a href="#" class="list-group-item active">
    Listing Projects
  </a>
  <a href="#" class="list-group-item"><p>
  <strong>Title:</strong>
  <%= @building.title %>
</p></a>
  <a href="#" class="list-group-item"><p>
  <strong>Description:</strong>
  <%= @building.description %>
</p></a>
  <a href="#" class="list-group-item"><p>
  <strong>Total budget:</strong>
  <%= @building.total_budget %>
</p></a>
  <a href="#" class="list-group-item"><p>
  <strong>Discount:</strong>
  <%= @building.discount %>
</p></a>
    <a href="#" class="list-group-item"><p>
  <strong>Discount:</strong>
  <%= @building.discount %>
</p></a>
      <a href="#" class="list-group-item"><p>
  <strong>User:</strong>
  <%= @building.user.try(:name) %>
</p></a>
</div>













<div class="panel panel-danger">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3>Listing Installments</h3></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>building</th>
      <th>Amount</th>
      <th>Installment date</th>
      <th>Status</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @building.installments.each do |installment| %>
    <tr>
      <td><%= installment.building_id %></td>
      <td><%= installment.amount %></td>
      <td><%= installment.installment_date %></td>
      <td><%= installment.status %></td>
      <td><%= installment.details %></td>
      <% if installment.status != "paid" %>
      <td><%= link_to 'Pay', buildings_paid_path(:installment_id => installment.id) %></td>
      <td><%= link_to 'Edit', edit_installment_path(installment) %></td>
      <td><%= link_to 'Destroy', installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>

      <td><%= link_to 'Edit', edit_installment_path(installment) %></td>
      <td><%= link_to 'Destroy', installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>





</div>
</div>
<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>